## What is TensorFlow?

[TensorFlow](https://www.tensorflow.org/) is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

## Why use TensorFlow?

Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as TensorFlow. This is because it contains many of the most common machine learning functions you'll want to use.

## What we're going to cover

TensorFlow is vast. But the main premise is simple: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them.

In this notebook we cover some of the most fundamental TensorFlow operations, more specificially:
* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow

Things to note:
* Many of the conventions here will happen automatically behind the scenes (when you build a model) but it's worth knowing so if you see any of these things, you know what's happening.
* For any TensorFlow function you see, it's important to be able to check it out in the documentation, for example, going to the Python API docs for all functions and searching for what you need: https://www.tensorflow.org/api_docs/python/ 


#### Installing Tensorflow:

`https://www.tensorflow.org/install`

In [1]:
# Run command below to Install Tensorflow directly from jupyter Notebook:

#!pip install tensorflow --user

##### Alternatively, open Anaconda Prompt (as Administrator) and run below code:

In [2]:
# pip install tensorflow

#### Importing Tensorflow and Checking it's Version:

In [3]:
import tensorflow as tf

2026-01-02 12:56:34.557836: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-02 12:56:36.384474: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-02 12:56:41.079236: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/home/shail/miniconda3/envs/tf-gpu/lib/python3.11/site-packages/keras/src/export/tf2onnx_li

In [4]:
tf.__version__

'2.20.0'

### Creating Tensors with `tf.constant()`

In general, you usually won't create tensors yourself. This is because TensorFlow has modules built-in (such as [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) and [`tf.data`](https://www.tensorflow.org/guide/data)) which are able to read your data sources and automatically convert them to tensors and then later on, neural network models will process these for us.

But for now, because we're getting familar with tensors themselves and how to manipulate them, we'll see how we can create them ourselves.

We'll begin by using [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).

In [5]:
# Creating a Scalar (Rank 0 Tensor):

scaler = tf.constant(10)
scaler

I0000 00:00:1767358607.951772    1275 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9507 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
# Checking Number of Dimensions of a Tensor ( ndim stands for Number of Dimensions)
scaler.ndim

0

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

> 🔑 **Note:** For now, we don't need to know too much about the different ranks of tensors (but we will see more on this later). The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

In [7]:
# Creating a Vector (More than 0 Dimensions):

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Checking Number of Dimensions:

vector.ndim

1

In [9]:
# Creating a Matrix (More than 1 Dimension):

matrix1 = tf.constant([[1,2],
                      [3,4]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
matrix1.ndim

2

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype.

This is known as [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science)) (the higher the precision, the more precise the number, the more space it takes up on your computer).

In [11]:
# Another Matrix, defining datatype explicitly:

matrix2 = tf.constant([[1.2, 2.1],
                      [2.3, 3.2],
                      [3.4, 4.3]], dtype= tf.float16)
matrix2

2026-01-02 12:56:52.111719: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1.2, 2.1],
       [2.3, 3.2],
       [3.4, 4.3]], dtype=float16)>

In [12]:
matrix2.ndim

2

In [13]:
# Creating a Tensor (More than 2 Dimensions. Although technically, all of the above items are also Tensors):

tensor = tf.constant([[[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    
                    [[10,11,12],
                    [13,14,15],
                    [16,17,18]],
                    
                    [[19,20,21],
                    [22,23,24],
                    [25,26,27]]])

tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

In [14]:
tensor.ndim

3

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
* 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
* 3 is the number of colour channels of the image (red, green blue).
* 32 is the batch size (the number of images a neural network sees at any one time).

All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):
* **scalar**: a single number.
* **vector**: a number with direction (e.g. wind speed with direction).
* **matrix**: a 2-dimensional array of numbers.
* **tensor**: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector). 

To add to the confusion, the terms matrix and tensor are often used interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Creating Tensors with `tf.Variable()`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).

In [15]:
# Creating same tensors with tf.variable and tf.constant:

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [16]:
# Trying to assign new value in Variable Tensor:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [20]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
# Trying to assign new value to a Constant Tensor:
unchangeable_tensor[0].assign[7]

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).

#### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

Why would you want to create random tensors? 

This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

**How a network learns**
![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png)
*A network learns by starting with random patterns (1) then going through demonstrative examples of data (2) whilst trying to update its random patterns to represent the examples (3).*

We can create random tensors by using the [`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class) class.

In [22]:
# Creating Two Random but same Tensors by Using Seed:

rndm_tensor1 = tf.random.Generator.from_seed(42)
rndm_tensor1 = rndm_tensor1.uniform(shape= (3,3))

rndm_tensor2 = tf.random.Generator.from_seed(42)
rndm_tensor2 = rndm_tensor2.uniform(shape= (3,3))

In [23]:
print(rndm_tensor1)
print(rndm_tensor2)

tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]
 [0.8736881  0.46921718 0.63932586]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]
 [0.8736881  0.46921718 0.63932586]], shape=(3, 3), dtype=float32)


The random tensors we've made are actually [pseudorandom numbers](https://www.computerhope.com/jargon/p/pseudo-random.htm) (they appear as random, but really aren't).

If we set a seed we'll get the same random numbers (if you've ever used NumPy, this is similar to `np.random.seed(42)`). 

Setting the seed says, "hey, create some random numbers, but flavour them with X" (X is the seed).

What do you think will happen when we change the seed?

In [24]:
rndm_tensor3 = tf.random.Generator.from_seed(42)
rndm_tensor3 = rndm_tensor3.normal(shape= (3,3))

rndm_tensor4 = tf.random.Generator.from_seed(7)
rndm_tensor4 = rndm_tensor4.normal(shape= (3,3))

In [25]:
print(rndm_tensor3)
print(rndm_tensor4)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535806 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-1.3240396   0.2878567  -0.87579006]
 [-0.08857017  0.69211644  0.84215707]
 [-0.06378496  0.92800784 -0.6039789 ]], shape=(3, 3), dtype=float32)
