## What is TensorFlow?

[TensorFlow](https://www.tensorflow.org/) is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

## Why use TensorFlow?

Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as TensorFlow. This is because it contains many of the most common machine learning functions you'll want to use.

## What we're going to cover

TensorFlow is vast. But the main premise is simple: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them.

In this notebook we cover some of the most fundamental TensorFlow operations, more specificially:
* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow

Things to note:
* Many of the conventions here will happen automatically behind the scenes (when you build a model) but it's worth knowing so if you see any of these things, you know what's happening.
* For any TensorFlow function you see, it's important to be able to check it out in the documentation, for example, going to the Python API docs for all functions and searching for what you need: https://www.tensorflow.org/api_docs/python/ 


#### Installing Tensorflow:

`https://www.tensorflow.org/install`

In [1]:
# Run command below to Install Tensorflow directly from jupyter Notebook:

#!pip install tensorflow --user

##### Alternatively, open Anaconda Prompt (as Administrator) and run below code:

In [4]:
# pip install tensorflow

#### Importing Tensorflow and Checking it's Version:

In [2]:
import tensorflow as tf

C:\Users\shail\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [3]:
tf.__version__

'2.20.0'

### Creating Tensors with `tf.constant()`

In general, you usually won't create tensors yourself. This is because TensorFlow has modules built-in (such as [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) and [`tf.data`](https://www.tensorflow.org/guide/data)) which are able to read your data sources and automatically convert them to tensors and then later on, neural network models will process these for us.

But for now, because we're getting familar with tensors themselves and how to manipulate them, we'll see how we can create them ourselves.

We'll begin by using [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).

In [5]:
# Creating a Scalar (Rank 0 Tensor):

scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
# Checking Number of Dimensions of a Tensor ( ndim stands for Number of Dimensions)
scaler.ndim

0

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

> 🔑 **Note:** For now, we don't need to know too much about the different ranks of tensors (but we will see more on this later). The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

In [7]:
# Creating a Vector (More than 0 Dimensions):

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Checking Number of Dimensions:

vector.ndim

1

In [9]:
# Creating a Matrix (More than 1 Dimension):

matrix1 = tf.constant([[1,2],
                      [3,4]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
matrix1.ndim

2

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype.

This is known as [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science)) (the higher the precision, the more precise the number, the more space it takes up on your computer).

In [11]:
# Another Matrix, defining datatype explicitly:

matrix2 = tf.constant([[1.2, 2.1],
                      [2.3, 3.2],
                      [3.4, 4.3]], dtype= tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1.2, 2.1],
       [2.3, 3.2],
       [3.4, 4.3]], dtype=float16)>

In [12]:
matrix2.ndim

2

In [14]:
# Creating a Tensor (More than 2 Dimensions. Although technically, all of the above items are also Tensors):

tensor = tf.constant([[[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    
                    [[10,11,12],
                    [13,14,15],
                    [16,17,18]],
                    
                    [[19,20,21],
                    [22,23,24],
                    [25,26,27]]])

tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

In [15]:
tensor.ndim

3

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
* 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
* 3 is the number of colour channels of the image (red, green blue).
* 32 is the batch size (the number of images a neural network sees at any one time).

All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):
* **scalar**: a single number.
* **vector**: a number with direction (e.g. wind speed with direction).
* **matrix**: a 2-dimensional array of numbers.
* **tensor**: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector). 

To add to the confusion, the terms matrix and tensor are often used interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)