# Numpy:

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

In [1]:
# importing Numpy:
import numpy as np

In [2]:
# Checking Installed Version of Numpy:
print(np.__version__)

2.3.2


In [3]:
# Upgrading Numpy to Latest Version:
!pip install --upgrade numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/d5/03/0eade211c504bda872a594f045f98ddcc6caef2b7c63610946845e304d3f/numpy-2.3.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 640.0 kB/s eta 0:00:01
     ---------------------------------------- 60.9/60.9 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/13.1 MB 2.6 MB/s eta 0:00:05
    --------------------------------------- 0.2/13.1 MB 3.6 MB/s eta 0:00:04
   - -------------------------------------- 0.5/13.1 MB 4.2 MB/s eta 0:00:03
   - -------------------------------------- 0.6/13.1 MB 4.1 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/13.1 MB 3.9 MB/s eta 0:00:04
   --- ------------------------------------ 1.1/13.1 MB 4.4 MB/s eta 0:00:03
   --- -------------------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
transformers 2.1.1 requires sentencepiece, which is not installed.
tensorflow-intel 2.16.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.3.2 which is incompatible.
numba 0.57.0 requires numpy<1.25,>=1.21, but you have numpy 2.3.2 which is incompatible.
scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you have numpy 2.3.2 which is incompatible.


In [3]:
# Creating 1D Array Using Numpy:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# Creating 2D Array Using Numpy:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
a = np.array([1,2,3], dtype= 'float')
print(a)

[1. 2. 3.]


In [7]:
a = np.array([1,2,3], dtype= 'str')
print(a)

['1' '2' '3']


In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(len(b))

[[1 2 3]
 [4 5 6]]
2


In [13]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(len(c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [12]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [14]:
d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(d)
print(d.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
4


### Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to __50x__ faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

In [15]:
# Shape of Array:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(3,)
(2, 3)
(3, 3)
(1, 1, 4, 3)


In [16]:
# Datatype pf Array:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

<U1
int64
int64
int64


### Accessing/Changing specific elements, rows & columns etc.

In [27]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
int64
2


In [20]:
# Accessing a Specific Element:
print(a[0,3])
print(a[1,6])

4
14


In [22]:
# Accessing a Specific Row:
print(a[0,:])
print(a[1,:])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [25]:
# Accessing a Specific Column:
print(a[:,0])
print(a[:,1])
print(a[:,2])
print(a[:,3])
print(a[:,4])
print(a[:,5])
print(a[:,6])

[1 8]
[2 9]
[ 3 10]
[ 4 11]
[ 5 12]
[ 6 13]
[ 7 14]


In [28]:
# Changing A value:
print(a)

a[0,1] = 100

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[  1 100   3   4   5   6   7]
 [  8   9  10  11  12  13  14]]


In [29]:
a[0,5] = 500
print(a)

[[  1 100   3   4   5 500   7]
 [  8   9  10  11  12  13  14]]


### Zeros/Ones method in NumPy

In [30]:
# Getting an Array filled with Zeroes:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
z = np.zeros((3,3), dtype = 'int32')
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
# Getting an Array Filled With Ones:
o = np.ones((3,3), dtype= 'int')
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [35]:
# Getting an Array filled with Specific Value:
s = np.full((3,3), 50)
print(s)

[[50 50 50]
 [50 50 50]
 [50 50 50]]


In [36]:
# Array of Random Numbers:
r = np.random.rand(4,4)
print(r)

[[0.00121752 0.71583614 0.97466294 0.28232598]
 [0.0392315  0.95176842 0.71530455 0.2385428 ]
 [0.56107188 0.06640675 0.23224059 0.56280917]
 [0.31070635 0.2524684  0.00879998 0.56676454]]


In [37]:
ri = np.random.randint(low= 0, high=10, size= (2,5))
print(ri)

[[2 8 9 7 3]
 [3 4 0 0 4]]


In [38]:
# Identity Matrix:
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Practice Questions:

##### Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [39]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [42]:
print(a[:3, -5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


##### Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 2:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [46]:
n = int(input("Enter an Odd Number greater than 2: "))

arr = np.zeros((n,n), dtype = 'int')

# Making the middle row and column elements or Array 1:
arr[n//2, :] = 1
arr[:, n//2] = 1

print(arr)

Enter an Odd Number greater than 2:  7


[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


### Arithmetic Operations with NumPy:

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [49]:
print(a + 2)
print(a - 2)
print(a / 2)
print(a * 2)
print(a ** 2)
print(a // 2)

[3 4 5 6]
[-1  0  1  2]
[0.5 1.  1.5 2. ]
[2 4 6 8]
[ 1  4  9 16]
[0 1 1 2]


In [50]:
# Minimum From Array:
print(a.min())
print(np.min(a))

1
1


In [51]:
# Minimum From Array:
print(a.max())
print(np.max(a))

4
4


In [52]:
# Average:
print(a.mean())
print(np.mean(a))

2.5
2.5


In [53]:
# Standard Deviation:
print(a.std())
print(np.std(a))

1.118033988749895
1.118033988749895


In [54]:
# Variance:
print(a.var())
print(np.var(a))

1.25
1.25
