# Descriptive Statistics Using Numpy

In [1]:
import numpy as np

#### Descriptive Statistics of List using Numpy:

In [2]:
lst = [12, 15, 17, 90, 31, 42, 54, 32, 12, 12]

In [3]:
# Mean:

np.mean(lst)

31.7

In [4]:
# Median:

np.median(lst)

24.0

In [5]:
# Standard Deviation:

np.std(lst)

23.795167576632025

In [6]:
# Variance:

np.var(lst)

566.21

#### Descriptive Statistics of 1-D Array using Numpy:

In [7]:
array_1d = np.random.randint(0, 50, 25)

In [8]:
print(array_1d)

[ 4  3 18 13 44 24  8 18  7  7 19 15 10  0 25  6 17 22 10 17 20 11 10 26
 10]


In [10]:
# Mean:
print(np.mean(array_1d))
print(array_1d.mean())

14.56
14.56


In [14]:
# Median:
print(np.median(array_1d))

13.0


In [15]:
# Variance:
print(np.var(array_1d))
print(array_1d.var())

84.8864
84.8864


In [16]:
# Standard Deviation:
print(np.std(array_1d))
print(array_1d.std())

9.21338157247381
9.21338157247381


#### Descriptive Statistics of 2-D Array using Numpy:

In [17]:
array_2d = array_1d.reshape(5,5)
print(array_2d)

[[ 4  3 18 13 44]
 [24  8 18  7  7]
 [19 15 10  0 25]
 [ 6 17 22 10 17]
 [20 11 10 26 10]]


In [18]:
# Mean of All Elements:
print(np.mean(array_2d))
print(array_2d.mean())

14.56
14.56


In [19]:
# Median of All Elements:
print(np.median(array_2d))

13.0


In [20]:
# Variance of All Elements:
print(np.var(array_2d))
print(array_2d.var())

84.8864
84.8864


In [21]:
# Standard Deviation of All Elements:
print(np.std(array_2d))
print(array_2d.std())

9.21338157247381
9.21338157247381


##### Descriptive Stats Across Rows / Columns of 2-D Array:
    axis = 0 : Across The Rows
    axis = 1 : Across The Columns

In [22]:
print(array_2d)

[[ 4  3 18 13 44]
 [24  8 18  7  7]
 [19 15 10  0 25]
 [ 6 17 22 10 17]
 [20 11 10 26 10]]


In [23]:
# Mean Across Rows:
print(np.mean(array_2d, axis= 0))
print(array_2d.mean(axis= 0))

[14.6 10.8 15.6 11.2 20.6]
[14.6 10.8 15.6 11.2 20.6]


In [24]:
# Mean Across Columns:
print(np.mean(array_2d, axis= 1))
print(array_2d.mean(axis= 1))

[16.4 12.8 13.8 14.4 15.4]
[16.4 12.8 13.8 14.4 15.4]


In [26]:
# Median Acroass Rows:
print(np.median(array_2d, axis= 0))

[19. 11. 18. 10. 17.]


In [27]:
# Median Across Columns:
print(np.median(array_2d, axis= 1))

[13.  8. 15. 17. 11.]


In [28]:
# Variance Across Rows:
print(np.var(array_2d, axis= 0))
print(array_2d.var(axis= 0))

[ 64.64  24.96  23.04  73.36 175.44]
[ 64.64  24.96  23.04  73.36 175.44]


In [29]:
# Variance Across Columns:
print(np.var(array_2d, axis= 1))
print(array_2d.var(axis= 1))

[221.84  48.56  71.76  32.24  42.24]
[221.84  48.56  71.76  32.24  42.24]


In [30]:
# Standard Deviation Across Rows:
print(np.std(array_2d, axis= 0))
print(array_2d.std(axis= 0))

[ 8.0399005   4.9959984   4.8         8.56504524 13.24537655]
[ 8.0399005   4.9959984   4.8         8.56504524 13.24537655]


In [31]:
# Standard Deviation Across Columns:
print(np.std(array_2d, axis= 1))
print(array_2d.std(axis= 1))

[14.89429421  6.96850056  8.47112743  5.67802783  6.49923072]
[14.89429421  6.96850056  8.47112743  5.67802783  6.49923072]
